format_version: 10
pipelines:
  pingpong_infra_provisioning:
    group: RHTWD_infra_provisioning
    label_template: "${COUNT}-${infra_provisioning[:7]}"
    lock_behavior: unlockWhenFinished
    display_order: -1
    materials:
      infra_provisioning:
        git: https://github.com/rahul-rakshit/rhtwd-infra
        shallow_clone: false
        auto_update: true
        branch: trunk
      upstream:
        pipeline: pingpong_build
        stage: docker_push
        name: upstream
    stages:
      - terraform:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: true
          approval:
            type: success
            allow_only_on_success: false
          jobs:
            terraform:
              timeout: 0
              tasks:
                - exec:
                    command: /bin/bash
                    working_directory: pingpong_provisioning/terraform
                    arguments:
                      - "-c"
                      - "terraform init -input=false"
                  run_if: passed
                - exec:
                    command: /bin/bash
                    working_directory: pingpong_provisioning/terraform
                    arguments:
                      - "-c"
                      - "terraform validate"
                  run_if: passed
                - exec:
                    command: /bin/bash
                    working_directory: pingpong_provisioning/terraform
                    arguments:
                      - "-c"
                      - "terraform plan -out=tfplan -input=false"
                  run_if: passed
                - exec:
                    command: /bin/bash
                    working_directory: pingpong_provisioning/terraform
                    arguments:
                      - "-c"
                      - "terraform apply -input=false tfplan"
                  run_if: passed
