format_version: 10
pipelines:
  dummy_secret_provisioning:
    group: RHTWD_infra_provisioning
    label_template: "${COUNT}-${infra_provisioning[:7]}"
    lock_behavior: unlockWhenFinished
    display_order: -1
    environment_variables:
      CHINESE_HELLO: 你好
    materials:
      infra_provisioning:
        git: https://github.com/rahul-rakshit/rhtwd-infra
        shallow_clone: false
        auto_update: true
        branch: trunk
        includes:
          - dummy_secret_provisioning/**/*
    stages:
      - terraform:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: true
          approval:
            type: success
            allow_only_on_success: false
          jobs:
            terraform:
              timeout: 0
              tasks:
                - exec:
                  working_directory: dummy_secret/terraform
                  run_if: passed
                  command: /bin/bash
                  arguments:
                    - -c
                    - terraform init
                - exec:
                  run_if: passed
                  working_directory: dummy_secret/terraform
                  command: /bin/bash
                  arguments:
                    - -c
                    - terraform validate
                - exec:
                  working_directory: dummy_secret/terraform
                  run_if: passed
                  command: /bin/bash
                  arguments:
                    - -c
                    - >
                      terraform plan -var namespace=staging -out=tfplan-$GO_PIPELINE_LABEL
                - exec:
                  working_directory: dummy_secret/terraform
                  run_if: passed
                  command: /bin/bash
                  arguments:
                    - -c
                    - >
                      terraform apply
                      fplan-$GO_PIPELINE_LABEL
