format_version: 10
pipelines:
  dummy_secret_provisioning:
    group: RHTWD_infra_provisioning
    label_template: "${COUNT}-${infra_provisioning[:7]}"
    lock_behavior: unlockWhenFinished
    display_order: -1
    environment_variables:
      # CHINESE_HELLO: 你好
      # CHINESE_GOODBYE: 再见
      CHINESE_HELLO: Bonjour
      CHINESE_GOODBYE: Au revoir
    materials:
      infra_provisioning:
        git: https://github.com/rahul-rakshit/rhtwd-infra
        shallow_clone: false
        auto_update: true
        branch: trunk
        includes:
          - dummy_secret/**/*
    stages:
      - terraform:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: true
          approval:
            type: success
            allow_only_on_success: false
          jobs:
            terraform:
              timeout: 0
              tasks:
                - exec:
                    working_directory: dummy_secret/terraform
                    command: /bin/bash
                    arguments:
                      - -c
                      - terraform init
                  run_if: passed
                - exec:
                    working_directory: dummy_secret/terraform
                    command: /bin/bash
                    arguments:
                      - -c
                      - >
                        terraform plan
                        -var chinese_hello=$CHINESE_HELLO
                        -var chinese_goodbye=$CHINESE_GOODBYE
                        -out="tfplan-$GO_PIPELINE_LABEL" 
                  run_if: passed
                - exec:
                    working_directory: dummy_secret/terraform
                    command: /bin/bash
                    arguments:
                      - -c
                      - terraform apply "tfplan-$GO_PIPELINE_LABEL" 
                  run_if: passed
