format_version: 10
pipelines:
  pingpong_infra_provisioning:
    group: RHTWD_infra_provisioning
    label_template: "${COUNT}-${infra_provisioning[:7]}"
    lock_behavior: unlockWhenFinished
    display_order: -1
    materials:
      infra_provisioning:
        git: https://github.com/rahul-rakshit/rhtwd-infra
        shallow_clone: false
        auto_update: true
        branch: trunk
        material_name: infra_provisioning
    stages:
      - echo_go_env_vars:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: true
          approval:
            type: success
            allow_only_on_success: false
          jobs:
            echo_go_env_vars:
              timeout: 0
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - "-c"
                      - "./echo_env_vars"
                  run_if: passed
