format_version: 10
pipelines:
  pingpong:
    group: RHTWD_infra_provisioning
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      pingpong_infra_provisioning:
        git: https://github.com/rahul-rakshit/rhtwd-infra
        shallow_clone: false
        auto_update: true
        branch: trunk
    stages:
      - echo_go_env_vars:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: true
          approval:
            type: success
            allow_only_on_success: false
          jobs:
            echo_go_env_vars:
              timeout: 0
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - "-c"
                      - "echo revision: $GO_REVISION"
                  run_if: passed
                - exec:
                    command: /bin/bash
                    arguments:
                      - "-c"
                      - "echo label: $GO_PIPELINE_LABEL"
