format_version: 10
pipelines:
  cassowary_provisioning:
    group: RHTWD_infra_provisioning
    label_template: "${COUNT}-${infra_provisioning[:7]}"
    lock_behavior: unlockWhenFinished
    display_order: -1
    materials:
      infra_provisioning:
        git: https://github.com/rahul-rakshit/rhtwd-infra
        shallow_clone: false
        auto_update: true
        branch: trunk
        includes:
          - cassowary_provisioning/**/*
      cassowary_build:
        pipeline: cassowary_build
        stage: docker_push
        name: CASSOWARY_BUILD
    stages:
      - terraform:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: true
          approval:
            type: success
            allow_only_on_success: false
          jobs:
            terraform:
              timeout: 0
              tasks:
                - exec:
                    command: /bin/bash
                    working_directory: cassowary_provisioning/terraform
                    arguments:
                      - -c
                      - terraform init -input=false
                  run_if: passed
                - exec:
                    command: /bin/bash
                    working_directory: cassowary_provisioning/terraform
                    arguments:
                      - -c
                      - terraform validate
                  run_if: passed
                - exec:
                    command: /bin/bash
                    working_directory: cassowary_provisioning/terraform
                    arguments:
                      - -c
                      - >
                        terraform plan
                        -var build_label=$GO_DEPENDENCY_LABEL_CASSOWARY_BUILD
                        -out=tfplan-$GO_DEPENDENCY_LABEL_CASSOWARY_BUILD
                        -input=false
                  run_if: passed
                - exec:
                    command: /bin/bash
                    working_directory: cassowary_provisioning/terraform
                    arguments:
                      - -c
                      - >
                        terraform apply
                        -input=false
                        tfplan-$GO_DEPENDENCY_LABEL_CASSOWARY_BUILD
                  run_if: passed
